/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-03 05:44:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex_005frsv_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/JSPstydy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GitProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<title>Plus Admin</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/jquery-bar-rating/css-stars.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/font-awesome/css/font-awesome.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"assets/images/favicon.png\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- CSS 수정영역 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/reserv/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/reserv/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/reserv/owl.theme.default.min.css\">\r\n");
      out.write("<link href=\"assets/css/demo_1/reserv/templatemo-pod-talk.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<<<<<<< HEAD\r\n");
      out.write("<style>\r\n");
      out.write("#my_modal {\r\n");
      out.write("	position: relative; /* 모달 내부의 상대적인 위치 설정 */\r\n");
      out.write("	display: none;\r\n");
      out.write("	width: 650px;\r\n");
      out.write("	height: 900px;\r\n");
      out.write("	padding: 20px 60px;\r\n");
      out.write("	background-color: #fefefe;\r\n");
      out.write("	border: 3px solid #333333;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my_modal .modal_close_btn {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 10px;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scrollable-section {\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("	max-height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#reservation_section {\r\n");
      out.write("	border: 3px solid #333333;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#vc_border {\r\n");
      out.write("	border: 3px solid #333333;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#vc_price_modal, #rsv_date {\r\n");
      out.write("	border: 3px solid #333333; /* 테두리 추가 */\r\n");
      out.write("	padding: 10px; /* 내부 여백 설정 */\r\n");
      out.write("	border-radius: 5px; /* 테두리 모서리를 둥글게 만듭니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-block {\r\n");
      out.write("	border: 2px solid #333333\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#buy {\r\n");
      out.write("	margin-left: 410px;\r\n");
      out.write("	background-color: #D6D6D6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#reserve_button {\r\n");
      out.write("	margin-left: 410px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("=======\r\n");
      out.write("<link href=\"assets/css/demo_1/reserv/modal.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- *******************************  CSS Link 작업영역 END  ******************************* -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ********************  CSS 작업가능 영역 END *************************-->\r\n");
      out.write(">>>>>>> branch 'master' of https://github.com/2024-SMHRD-KDT-BigData-23/FitNeeds.git\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"my_modal\">\r\n");
      out.write("\r\n");
      out.write("		<div id=\"vc_border\">\r\n");
      out.write("			<h2 id=\"modal\"></h2>\r\n");
      out.write("			<br>\r\n");
      out.write("			<p id=\"vc_price_modal\"></p>\r\n");
      out.write("			<br> <br> <span id=\"total_price\">\r\n");
      out.write("		</div>\r\n");
      out.write("		</span><span id=\"buy\"></span> <br> <br>\r\n");
      out.write("		<div id=\"reservation_section\" class=\"scrollable-section\">\r\n");
      out.write("			<h2>PT 예약</h2>\r\n");
      out.write("			<br>\r\n");
      out.write("			<p id='rsv_date'></p>\r\n");
      out.write("			<p id='rsv_date_commit'></p>\r\n");
      out.write("			<input type='hidden' id=\"pt_commit\" name='pt_commit'> <input\r\n");
      out.write("				type='hidden' id=\"pt_status\"> <a class=\"modal_close_btn\">X</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"reserve_button\" name='pt_commit' class=\"custom-btn btn-16\">예약하기</button>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("	<!-- ** SIDE BAR SECTION ** -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-scroller\">\r\n");
      out.write("		<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\"><a href=\"UpdatePage.do\"\r\n");
      out.write("					class=\"nav-link flex-column\">\r\n");
      out.write("						<div class=\"nav-profile-image\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\r\n");
      out.write("							<!--change to offline or busy as needed-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\r\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\r\n");
      out.write("					href=\"MainPage.do\"> <img class=\"sidebar-brand-logo\"\r\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\r\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\r\n");
      out.write("						alt=\"\" />\r\n");
      out.write("						<div class=\"small font-weight-light pt-1\">fitness responsive\r\n");
      out.write("							web design</div>\r\n");
      out.write("				</a>\r\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\r\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\r\n");
      out.write("						</MENU>\r\n");
      out.write("				</span></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("				<!--*** side nar > nav >  사용자 Menu start ***-->\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"MainPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-compass-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ComparePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-chart-bar menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동비교</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"InputPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-check-circle menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동입력</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ReservePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<!--*** 사용자 Menu end ***-->\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- ** SIDE BAR SECTION END ** -->\r\n");
      out.write("		<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("		<!-- ** TOP BAR SECTION ** -->\r\n");
      out.write("\r\n");
      out.write("		<!-- partial -->\r\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("			<!-- partial:partials/_settings-panel.html -->\r\n");
      out.write("			<div id=\"settings-trigger\">\r\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\r\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\r\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\r\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\r\n");
      out.write("					Default\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\r\n");
      out.write("					Dark\r\n");
      out.write("				</div>\r\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\r\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\r\n");
      out.write("					<div class=\"tiles default primary\"></div>\r\n");
      out.write("					<div class=\"tiles success\"></div>\r\n");
      out.write("					<div class=\"tiles warning\"></div>\r\n");
      out.write("					<div class=\"tiles danger\"></div>\r\n");
      out.write("					<div class=\"tiles info\"></div>\r\n");
      out.write("					<div class=\"tiles dark\"></div>\r\n");
      out.write("					<div class=\"tiles light\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- partial -->\r\n");
      out.write("			<!-- partial:partials/_navbar.html -->\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"MainPage.do\"><img\r\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								<div class=\"nav-profile-text\">MYPAGE</div>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\r\n");
      out.write("								aria-labelledby=\"profileDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\r\n");
      out.write("								</a>\r\n");
      out.write("								<!-- 변경부분 -->\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\r\n");
      out.write("								</a>\r\n");
      out.write("								<!-- 변경부분 -->\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\r\n");
      out.write("							class=\"nav-link\" href=\"MainPage.do\"> <i\r\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"main-panel\">\r\n");
      out.write("				<div class=\"content-wrapper pb-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"content-wrapper\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card1 \">\r\n");
      out.write("								<div class=\"\">\r\n");
      out.write("\r\n");
      out.write("									<section class=\"hero-section\">\r\n");
      out.write("										<div class=\"container\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-lg-12 col-12\">\r\n");
      out.write("\r\n");
      out.write("													<div class=\"owl-carousel owl-theme\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("														");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</section>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div id=\"placeholder_div\" class=\"container text-center mt-5\">\r\n");
      out.write("								<div class=\"border p-4\">\r\n");
      out.write("									<h4 class=\"mb-4\">트레이너를 선택해주세요</h4>\r\n");
      out.write("									<h5>트레이너 정보, 예약 섹션입니다.</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<section class=\"latest-podcast-section section-padding pb-0\"\r\n");
      out.write("								id=\"section_2\">\r\n");
      out.write("								<div class=\"container\">\r\n");
      out.write("									<div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-lg-12 col-12\">\r\n");
      out.write("											<div class=\"section-title-wrap mb-5\">\r\n");
      out.write("												<h4 class=\"section-title\">트레이너 상세정보</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-lg-6 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("											<div class=\"custom-block d-flex\">\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"custom-block-icon-wrap\">\r\n");
      out.write("														<div class=\"section-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"custom-block-info\">\r\n");
      out.write("													<h5 class=\"mb-2\"></h5>\r\n");
      out.write("\r\n");
      out.write("													<div class=\"profile-block d-flex\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("														<div>\r\n");
      out.write("\r\n");
      out.write("															<p id=\"get_trn\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"trn_phone\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"trn_info\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"trn_career\" class=\"rev_font\"></p>\r\n");
      out.write("															<input type='hidden' id=\"trn_idx\">\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-lg-6 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("											<div class=\"custom-block d-flex\">\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"custom-block-icon-wrap\">\r\n");
      out.write("														<div class=\"section-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"custom-block-info\">\r\n");
      out.write("													<h5 class=\"mb-2\"></h5>\r\n");
      out.write("\r\n");
      out.write("													<div class=\"profile-block d-flex\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("														<div>\r\n");
      out.write("\r\n");
      out.write("															<p id=\"center_name\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"center_tel\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"center_addr\" class=\"rev_font\"></p>\r\n");
      out.write("															<p id=\"vc_price\" class=\"rev_font\"></p>\r\n");
      out.write("															<button id=\"popup_open_btn\">이용권 구매하기</button>\r\n");
      out.write("\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<input type=\"hidden\" name=\"get_vc_idx\" id=\"get_vc_idx\">\r\n");
      out.write("\r\n");
      out.write("					<footer class=\"footer\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("							<span\r\n");
      out.write("								class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\r\n");
      out.write("								© 2024 <a target=\"_blank\">Fitneeds</a>. All rights reserved.\r\n");
      out.write("							</span> <span\r\n");
      out.write("								class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">\r\n");
      out.write("								Fitneeds team & smhrd <i class=\"mdi mdi-heart text-danger\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</footer>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/jquery-bar-rating/jquery.barrating.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/flot/jquery.flot.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/flot/jquery.flot.categories.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/flot/jquery.flot.fillbetween.js\"></script>\r\n");
      out.write("		<script src=\"assets/vendors/flot/jquery.flot.stack.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/jquery.cookie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("		<script src=\"assets/js/off-canvas.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/misc.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/settings.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/todolist.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- modal js영역 -->\r\n");
      out.write("		<script src=\"assets/js/reserv/jquery.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/reserv/owl.carousel.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/reserv/custom.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/rsv.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/fitcenterinfo.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/voucher.js\"></script>\r\n");
      out.write("<<<<<<< HEAD\r\n");
      out.write("		<script>\r\n");
      out.write("			function modal(id) {\r\n");
      out.write("				var zIndex = 9999;\r\n");
      out.write("				var modal = document.getElementById(id);\r\n");
      out.write("\r\n");
      out.write("				// 모달 div 뒤에 희끄무레한 레이어\r\n");
      out.write("				var bg = document.createElement('div');\r\n");
      out.write("				bg.setStyle({\r\n");
      out.write("					position : 'fixed',\r\n");
      out.write("					zIndex : zIndex,\r\n");
      out.write("					left : '0px',\r\n");
      out.write("					top : '0px',\r\n");
      out.write("					width : '100%',\r\n");
      out.write("					height : '100%',\r\n");
      out.write("					overflow : 'auto',\r\n");
      out.write("					// 레이어 색갈은 여기서 바꾸면 됨\r\n");
      out.write("					backgroundColor : 'rgba(0,0,0,0.4)'\r\n");
      out.write("				});\r\n");
      out.write("				document.body.append(bg);\r\n");
      out.write("\r\n");
      out.write("				// 닫기 버튼 처리, 시꺼먼 레이어와 모달 div 지우기\r\n");
      out.write("				modal.querySelector('.modal_close_btn').addEventListener(\r\n");
      out.write("						'click', function() {\r\n");
      out.write("							bg.remove();\r\n");
      out.write("							modal.style.display = 'none';\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("				modal.setStyle({\r\n");
      out.write("					position : 'fixed',\r\n");
      out.write("					display : 'block',\r\n");
      out.write("					boxShadow : '0 2px 3px 0 rgba(34,36,38,0.15)',\r\n");
      out.write("\r\n");
      out.write("					// 시꺼먼 레이어 보다 한칸 위에 보이기\r\n");
      out.write("					zIndex : zIndex + 1,\r\n");
      out.write("\r\n");
      out.write("					// div center 정렬\r\n");
      out.write("					top : '50%',\r\n");
      out.write("					left : '50%',\r\n");
      out.write("					transform : 'translate(-50%, -50%)',\r\n");
      out.write("					msTransform : 'translate(-50%, -50%)',\r\n");
      out.write("					webkitTransform : 'translate(-50%, -50%)'\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// Element 에 style 한번에 오브젝트로 설정하는 함수 추가\r\n");
      out.write("			Element.prototype.setStyle = function(styles) {\r\n");
      out.write("				for ( var k in styles)\r\n");
      out.write("					this.style[k] = styles[k];\r\n");
      out.write("				return this;\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			document.getElementById('popup_open_btn').addEventListener('click',\r\n");
      out.write("					function() {\r\n");
      out.write("						// 모달창 띄우기\r\n");
      out.write("						modal('my_modal');\r\n");
      out.write("					});\r\n");
      out.write("		</script>\r\n");
      out.write("		<script>\r\n");
      out.write("			// 클릭 시 트레이너 섹션을 보여주는 함수\r\n");
      out.write("			function showTrainerSection() {\r\n");
      out.write("				var section = document.getElementById('section_2');\r\n");
      out.write("				var placeholderDiv = document.getElementById('placeholder_div');\r\n");
      out.write("				section.style.display = 'block';\r\n");
      out.write("				placeholderDiv.style.display = 'none';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 트레이너를 선택하는 요소 클릭 시 트레이너 섹션을 보여주고 기본 문구를 숨김\r\n");
      out.write("			var trainerElements = document\r\n");
      out.write("					.querySelectorAll('.owl-carousel-info-wrap.item');\r\n");
      out.write("			trainerElements.forEach(function(element) {\r\n");
      out.write("				element.addEventListener('click', function() {\r\n");
      out.write("					showTrainerSection();\r\n");
      out.write("					var placeholderDiv = document\r\n");
      out.write("							.getElementById('placeholder_div');\r\n");
      out.write("					placeholderDiv.style.display = 'none';\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 페이지 로드 시 기본적으로 트레이너를 선택해주세요 문구를 보여줌\r\n");
      out.write("			document.addEventListener('DOMContentLoaded',\r\n");
      out.write("					function() {\r\n");
      out.write("						var section = document.getElementById('section_2');\r\n");
      out.write("						var placeholderDiv = document\r\n");
      out.write("								.getElementById('placeholder_div');\r\n");
      out.write("						section.style.display = 'none';\r\n");
      out.write("						placeholderDiv.style.display = 'block';\r\n");
      out.write("					});\r\n");
      out.write("		</script>\r\n");
      out.write("=======\r\n");
      out.write("		<script src=\"assets/js/modal.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--  *******************************  JS작업영역 END *******************************  -->\r\n");
      out.write("		<!-- ******************** JS 작업가능 영역 END *************************-->\r\n");
      out.write(">>>>>>> branch 'master' of https://github.com/2024-SMHRD-KDT-BigData-23/FitNeeds.git\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/Views/ex_rsv.jsp(311,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("trainer");
      // /WEB-INF/Views/ex_rsv.jsp(311,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Views/ex_rsv.jsp(311,14) '${trainer_info}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${trainer_info}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("															");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("														");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Views/ex_rsv.jsp(312,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainer.trn_name != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("																<div class=\"owl-carousel-info-wrap item\"\r\n");
          out.write("																	id=\"selectTrainer\">\r\n");
          out.write("																	<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainer.trn_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("																		class=\"owl-carousel-image img-fluid\" alt=\"\">\r\n");
          out.write("																	<div class=\"owl-carousel-info\">\r\n");
          out.write("																		<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainer.trn_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4>\r\n");
          out.write("																		<span class=\"btn btn-outline-primary btn-fw\">\r\n");
          out.write("																			#헬스 </span> <span class=\"btn btn-outline-danger btn-fw\">\r\n");
          out.write("																			");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainer.trn_info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </span>\r\n");
          out.write("																	</div>\r\n");
          out.write("																</div>\r\n");
          out.write("															");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
