/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-20 07:01:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/join.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script> \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ko.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        flatpickr('#birthdate', {\r\n");
      out.write("            dateFormat: \"Y-m-d\",\r\n");
      out.write("            maxDate: new Date().fp_incr(-1),\r\n");
      out.write("            locale: 'ko'\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function showLoginForm() {\r\n");
      out.write("        document.getElementById('join-form').style.display = 'none';\r\n");
      out.write("        document.getElementById('login-form').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showJoinForm() {\r\n");
      out.write("        document.getElementById('login-form').style.display = 'none';\r\n");
      out.write("        document.getElementById('join-form').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"panel shadow1\">\r\n");
      out.write("            <form id=\"join-form\" class=\"join-form\" action=\"Join.do\" method=\"post\">\r\n");
      out.write("                <!-- íìê°ì í¼ ë´ì© -->\r\n");
      out.write("                <div class=\"panel-switch animated fadeIn\">\r\n");
      out.write("                    <button type=\"button\" id=\"sign_up\" class=\"active-button\" onclick=\"showLoginForm()\">Log in</button>\r\n");
      out.write("                    <button type=\"button\" id=\"log_in\" class=\"active-button\" onclick=\"showJoinForm()\">Sign Up</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"animated fadeInUp animate1\" id=\"title-login\">FITNEEDS íìê°ì</h1>\r\n");
      out.write("                <fieldset id=\"login-fieldset\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate2\" class=\"loginfont\" name=\"mem_id\" type=\"text\" required placeholder=\"ìì´ë\" value=\"\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_pw\" type=\"password\" required placeholder=\"ë¹ë°ë²í¸\" value=\"\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_name\" type=\"text\" required placeholder=\"ì´ë¦\" value=\"\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_phone\" type=\"text\" required placeholder=\"000-0000-0000\" value=\"\"> \r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3 loginfont\" name=\"mem_birthdate\" type=\"text\" id=\"birthdate\" required placeholder=\"ìëìì¼\" value=\"\"> \r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_addr\" type=\"text\" required placeholder=\"ì£¼ì\" value=\"\"> \r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3 loginfont\" name=\"mem_email\" type=\"text\" required placeholder=\"ì´ë©ì¼\" value=\"\"> \r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_nick\" type=\"text\" required placeholder=\"ëë¤ì\" value=\"\"> \r\n");
      out.write("                    <select class=\"login animated fadeInUp animate3 loginfont\" name=\"mem_gender\" id=\"gender\" required>\r\n");
      out.write("                        <option value=\"M\">ë¨ì±</option>\r\n");
      out.write("                        <option value=\"F\">ì¬ì±</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"height\" type=\"text\" required placeholder=\"í¤\" value=\"\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"weight\" type=\"text\" required placeholder=\"ëª¸ë¬´ê²\" value=\"\">\r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <input type=\"submit\" id=\"login-form-submit\" class=\"login_form button animated fadeInUp animate4\" value=\"íìê°ì\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"panel shadow1\">\r\n");
      out.write("            <form id=\"login-form\" class=\"login-form\" action=\"login.do\" method=\"post\" style=\"display: none;\">\r\n");
      out.write("                <!-- ë¡ê·¸ì¸ í¼ ë´ì© -->\r\n");
      out.write("                <div class=\"panel-switch animated fadeIn\">\r\n");
      out.write("                    <button type=\"button\" id=\"sign_up\" class=\"active-button\" onclick=\"showLoginForm()\">Log in</button>\r\n");
      out.write("                    <button type=\"button\" id=\"log_in\" class=\"active-button\" onclick=\"showJoinForm()\">Sign Up</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"animated fadeInUp animate1\" id=\"title-login\">FITNEEDS ë¡ê·¸ì¸</h1>\r\n");
      out.write("                <fieldset id=\"login-fieldset\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate2\" class=\"loginfont\" name=\"mem_id\" type=\"text\" required placeholder=\"id\" value=\"\">\r\n");
      out.write("                    <input class=\"login animated fadeInUp animate3\" class=\"loginfont\" name=\"mem_pw\" type=\"password\" required placeholder=\"pw\" value=\"\">\r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <input type=\"submit\" id=\"login-form-submit\" class=\"login_form button animated fadeInUp animate4\" value=\"ë¡ê·¸ì¸\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
