/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-03 05:44:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myhealth_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<title>Plus Admin</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"assets/images/favicon.png\" />\r\n");
      out.write("<!-- ** 달력CSS START-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/calendar.css\" />\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		<div class=\"container-scroller\">\r\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\">\r\n");
      out.write("					<a href=\"UpdatePage.do\" class=\"nav-link flex-column\">\r\n");
      out.write("						<div class=\"nav-profile-image\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\r\n");
      out.write("							<!--change to offline or busy as needed-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\r\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\r\n");
      out.write("					href=\"MainPage.do\"> <img class=\"sidebar-brand-logo\"\r\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\r\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\r\n");
      out.write("						alt=\"\" />\r\n");
      out.write("						<div class=\"small font-weight-light pt-1\">\r\n");
      out.write("						fitness responsive web design\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\r\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\r\n");
      out.write("						</MENU>\r\n");
      out.write("				</span></li>\r\n");
      out.write("				<!--*** side nar > nav >  사용자 Menu start ***-->\r\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"MainPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-compass-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"ComparePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-chart-bar menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동비교</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"InputPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-check-circle menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동입력</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"ReservePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- partial -->\r\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("			<!-- partial:partials/_settings-panel.html -->\r\n");
      out.write("			<div id=\"settings-trigger\">\r\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\r\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\r\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\r\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\r\n");
      out.write("					Default\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\r\n");
      out.write("					Dark\r\n");
      out.write("				</div>\r\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\r\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\r\n");
      out.write("					<div class=\"tiles default primary\"></div>\r\n");
      out.write("					<div class=\"tiles success\"></div>\r\n");
      out.write("					<div class=\"tiles warning\"></div>\r\n");
      out.write("					<div class=\"tiles danger\"></div>\r\n");
      out.write("					<div class=\"tiles info\"></div>\r\n");
      out.write("					<div class=\"tiles dark\"></div>\r\n");
      out.write("					<div class=\"tiles light\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"MainPage.do\"><img\r\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								<div class=\"nav-profile-text\">MYPAGE</div></a>\r\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\r\n");
      out.write("								aria-labelledby=\"profileDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\r\n");
      out.write("							class=\"nav-link\" href=\"MainPage.do\"> <i\r\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("  <!-- partial 복사시작 복사시작 -->\r\n");
      out.write("      <div class=\"main-panel\">\r\n");
      out.write("        <div class=\"content-wrapper pb-0\">\r\n");
      out.write("          <!-- *********** my health form ******************* -->\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card card-exinput\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <form action=\"InputEx.do\" class=\"forms-sample\" method=\"post\" onsubmit=\"return validateForm();\">\r\n");
      out.write("                      <div class=\"login-form\">\r\n");
      out.write("                        <label for=\"exampleInputDate\">운동일자</label>\r\n");
      out.write("                        <input type=\"text\" name = \"ex_date\" class=\"form-control\" id=\"exampleInputDate\" placeholder=\"YYYY-MM-DD\" />\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- ì´ëì í-->\r\n");
      out.write("                      <div class=\"login-form\">\r\n");
      out.write("                        <label for=\"exampleFormControlSelect1\">운동선택</label>\r\n");
      out.write("                        <select name =\"ex_name\" class=\"form-control form-control-lg\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("                          <option>운동을 선택하세요.</option>\r\n");
      out.write("                          <option>아령운동</option>\r\n");
      out.write("                          <option>짐볼운동</option>\r\n");
      out.write("                          <option>바스키아운동전스트레칭</option>\r\n");
      out.write("                          <option>바스키아운동후스트레칭</option>\r\n");
      out.write("                          <option>스쿼트</option>\r\n");
      out.write("                          <option>턱걸이</option>\r\n");
      out.write("                          <option>런지</option>\r\n");
      out.write("                          <option>백익스텐션</option>\r\n");
      out.write("                          <option>사이드 싯업</option>\r\n");
      out.write("                          <option>크런치</option>\r\n");
      out.write("                          <option>힙업</option>\r\n");
      out.write("                          <option>바벨백익스텐션</option>\r\n");
      out.write("                          <option>벤드오버</option>\r\n");
      out.write("                          <option>이두덤벨컬</option>\r\n");
      out.write("                          <option>이두바벨컬</option>\r\n");
      out.write("                          <option>데드리프트</option>\r\n");
      out.write("                          <option>라잉레그컬</option>\r\n");
      out.write("                          <option>라잉힙업</option>\r\n");
      out.write("                          <option>레그레이즈</option>\r\n");
      out.write("                          <option>레그프레스</option>\r\n");
      out.write("                          <option>사이드밴드</option>\r\n");
      out.write("                          <option>양반크런치</option>\r\n");
      out.write("                          <option>체스트플라이</option>\r\n");
      out.write("                          <option>카프레이즈</option>\r\n");
      out.write("                          <option>트라이셉스킥백</option>\r\n");
      out.write("                          <option>레그익스텐션</option>\r\n");
      out.write("                          <option>바벨벤치프레스</option>\r\n");
      out.write("                          <option>사이드크런치</option>\r\n");
      out.write("                          <option>삼두바벨익스텐션</option>\r\n");
      out.write("                          <option>스텐딩힙업</option>\r\n");
      out.write("                          <option>컨센트레이션컬</option>\r\n");
      out.write("                          <option>바벨숄더프레스</option>\r\n");
      out.write("                          <option>삼두덤벨익스텐션</option>\r\n");
      out.write("                          <option>수잔파우터육체와의전쟁</option>\r\n");
      out.write("                          <option>디클라인벤치프레스</option>\r\n");
      out.write("                          <option>라잉사이드힙업</option>\r\n");
      out.write("                          <option>바벨프런트프레스</option>\r\n");
      out.write("                          <option>사이드레그레이즈</option>\r\n");
      out.write("                          <option>싯레그레이즈교차</option>\r\n");
      out.write("                          <option>인클라인벤치프레스</option>\r\n");
      out.write("                          <option>스텐딩사이드힙업</option>\r\n");
      out.write("                          <option>푸쉬업</option>\r\n");
      out.write("                          <option>바벨벤트오버로우모션</option>\r\n");
      out.write("                          <option>원핸드벤트오버로우모션</option>\r\n");
      out.write("                          <option>바벨트라이셉스익스텐션</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"login-form\">\r\n");
      out.write("                        <label for=\"exampleInputConfirmPassword1\">운동완료여부</label>\r\n");
      out.write("                        <div class=\"login-form row\">\r\n");
      out.write("                          <div class=\"col-sm-circle\">\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                              <label class=\"form-check-label\">\r\n");
      out.write("                                <input type=\"radio\" class=\"form-check-input\" name=\"ex_done\"\r\n");
      out.write("                                  id=\"membershipRadios1\" value=\"Y\" checked />운동완료</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-circle\">\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                              <label class=\"form-check-label\">\r\n");
      out.write("                                <input type=\"radio\" class=\"form-check-input\" name=\"ex_done\"\r\n");
      out.write("                                  id=\"membershipRadios2\" value=\"N\" />오늘은 쉴래요.</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"login-form\">\r\n");
      out.write("                        <label for=\"exampleInputConfirmPassword1\">반복횟수</label>\r\n");
      out.write("                        <input type=\"text\" name=\"ex_reps\" class=\"form-control\" id=\"exampleInputConfirmPassword2\"\r\n");
      out.write("                          placeholder=\"반복횟수\" />\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"login-form\">\r\n");
      out.write("                        <label for=\"exampleInputConfirmPassword1\">운동시간</label>\r\n");
      out.write("                        <input type=\"text\" name=\"ex_time\" class=\"form-control\" id=\"exampleInputConfirmPassword2\"\r\n");
      out.write("                          placeholder=\"운동시간\"/>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"comp\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary me-2\">운동완료</button>\r\n");
      out.write("                      <button type=\"reset\" class=\"btn btn-light\">취소</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("				<!-- partial:partials/_footer.html -->\r\n");
      out.write("        <footer class=\"footer\">\r\n");
      out.write("          <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("            <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2024 <a\r\n");
      out.write("                target=\"_blank\">Fitneeds</a>. All rights reserved.</span>\r\n");
      out.write("            <span class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\"> Fitneeds team & smhrd <i\r\n");
      out.write("                class=\"mdi mdi-heart text-danger\"></i></span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("			</div> <!-- main-panel ends --> \r\n");
      out.write("		</div><!-- page-body-wrapper ends -->\r\n");
      out.write("	</div><!-- container-scroller -->\r\n");
      out.write("	<!-- plugins:js -->\r\n");
      out.write("	<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/off-canvas.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/misc.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/settings.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/todolist.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/chart.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/check_ex.js\"></script>\r\n");
      out.write("		<!-- 달력 스크립트 START -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$(\"#exampleInputDate\").datepicker({\r\n");
      out.write("				dateFormat : \"yy-mm-dd\"\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
