/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-03 05:58:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class weight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- basic CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- weight CSS-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/weight.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/cssplus.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- calendar CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/calendar.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-scroller\">\r\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\"><a\r\n");
      out.write("					href=\"UpdatePage.do\" class=\"nav-link flex-column\">\r\n");
      out.write("						<div class=\"nav-profile-image\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\r\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\r\n");
      out.write("					href=\"fitindex.do\"> <img class=\"sidebar-brand-logo\"\r\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\r\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\r\n");
      out.write("						alt=\"\" />\r\n");
      out.write("						<div class=\"small font-weight-light pt-1\">fitness responsive\r\n");
      out.write("							web design</div>\r\n");
      out.write("				</a>\r\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\r\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\r\n");
      out.write("						</MENU>\r\n");
      out.write("				</span></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"MainPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-compass-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ComparePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-chart-bar menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동비교</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"InputPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-check-circle menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동입력</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ReservePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("			<div id=\"settings-trigger\">\r\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\r\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\r\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\r\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\r\n");
      out.write("					Default\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\r\n");
      out.write("					Dark\r\n");
      out.write("				</div>\r\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\r\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\r\n");
      out.write("					<div class=\"tiles default primary\"></div>\r\n");
      out.write("					<div class=\"tiles success\"></div>\r\n");
      out.write("					<div class=\"tiles warning\"></div>\r\n");
      out.write("					<div class=\"tiles danger\"></div>\r\n");
      out.write("					<div class=\"tiles info\"></div>\r\n");
      out.write("					<div class=\"tiles dark\"></div>\r\n");
      out.write("					<div class=\"tiles light\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"fitindex.do\"><img\r\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								<div class=\"nav-profile-text\">MYPAGE</div>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\r\n");
      out.write("								aria-labelledby=\"profileDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\r\n");
      out.write("								</a>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\r\n");
      out.write("								</a>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\r\n");
      out.write("							class=\"nav-link\" href=\"fitindex.do\"> <i\r\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"main-panel flower-panel\">\r\n");
      out.write("				<div class=\"content-wrapper\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-3 grid-margin stretch-card\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"card card-stat mb-3\"\r\n");
      out.write("										style=\"background-size: cover;\">\r\n");
      out.write("										<div class=\"card-body\">\r\n");
      out.write("											<div class=\"text\">\r\n");
      out.write("												<div class=\"flot-bar-wrapper\">\r\n");
      out.write("													<h6>WEIGHT CHANGE</h6>\r\n");
      out.write("													<h3 class=\"font-weight-bold\"\r\n");
      out.write("														style=\"background-color: #926168; color: #FFFFFF\">\r\n");
      out.write("														");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("													</h3>\r\n");
      out.write("													<h3 class=\"font-weight-bold\" id=\"month_img_content\"\r\n");
      out.write("														style=\"background-color: #FFFFFF; color: #926168\"></h3>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<form action=\"InputCh.do\" method=\"post\"\r\n");
      out.write("										onsubmit=\"return validateForm();\">\r\n");
      out.write("										<div class=\"login-form-flower\">\r\n");
      out.write("											<label class=\"text-talk\">체중을 언제 측정하셨나요? </i></label> <input\r\n");
      out.write("												type=\"text\" class=\"form-control\" id=\"exampleInputDate\"\r\n");
      out.write("												name=\"ch_date\" placeholder=\"YYYY-MM-DD\" /> <label\r\n");
      out.write("												class=\"text-talk\">측정한 체중을 입력해주세요 <i\r\n");
      out.write("												class=\"mdi mdi-heart text-danger\"></i>\r\n");
      out.write("											</label> <input type=\"text\" name=\"weight\" class=\"form-control\"\r\n");
      out.write("												id=\"exampleInputConfirmPassword2\" placeholder=\"체중(kg)\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"flower-submit\">\r\n");
      out.write("											<button type=\"submit\" class=\"badge badge-danger\"\r\n");
      out.write("												style=\"display: block; margin: 0 auto;\">운동완료</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<footer class=\"footer\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("						<span\r\n");
      out.write("							class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\r\n");
      out.write("							© 2024 <a target=\"_blank\">Fitneeds</a>. All rights reserved.\r\n");
      out.write("						</span> <span\r\n");
      out.write("							class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">\r\n");
      out.write("							Fitneeds team & smhrd <i class=\"mdi mdi-heart text-danger\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</footer>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/jquery-bar-rating/jquery.barrating.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/flot/jquery.flot.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/flot/jquery.flot.categories.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/flot/jquery.flot.fillbetween.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/flot/jquery.flot.stack.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.cookie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/off-canvas.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/misc.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/settings.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/todolist.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- calendar JS -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/check_ch.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/month_img.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
