/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-01 03:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chartjs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<title>Plus Admin</title>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End Plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/join/chartjs.css\" />\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-scroller\">\r\n");
      out.write("		<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link flex-column\">\r\n");
      out.write("						<div class=\"nav-profile-image\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\r\n");
      out.write("							<!--change to offline or busy as needed-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\r\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\r\n");
      out.write("					href=\"MainPage.do\"> <img class=\"sidebar-brand-logo\"\r\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\r\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\r\n");
      out.write("						alt=\"\" />\r\n");
      out.write("						<div class=\"small font-weight-light pt-1\">fitness responsive\r\n");
      out.write("							web design</div>\r\n");
      out.write("				</a>\r\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\r\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\r\n");
      out.write("						</MENU>\r\n");
      out.write("				</span></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("				<!--*** side nar > nav >  사용자 Menu start ***-->\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"MainPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-compass-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ComparePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-chart-bar menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동비교</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"InputPage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-check-circle menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동입력</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"ReservePage.do\">\r\n");
      out.write("						<i class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\r\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<!--*** 사용자 Menu end ***-->\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- ** SIDE BAR SECTION END ** -->\r\n");
      out.write("		<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("		<!-- ** TOP BAR SECTION ** -->\r\n");
      out.write("\r\n");
      out.write("		<!-- partial -->\r\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("			<!-- partial:partials/_settings-panel.html -->\r\n");
      out.write("			<div id=\"settings-trigger\">\r\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\r\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\r\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\r\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\r\n");
      out.write("					Default\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\r\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\r\n");
      out.write("					Dark\r\n");
      out.write("				</div>\r\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\r\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\r\n");
      out.write("					<div class=\"tiles default primary\"></div>\r\n");
      out.write("					<div class=\"tiles success\"></div>\r\n");
      out.write("					<div class=\"tiles warning\"></div>\r\n");
      out.write("					<div class=\"tiles danger\"></div>\r\n");
      out.write("					<div class=\"tiles info\"></div>\r\n");
      out.write("					<div class=\"tiles dark\"></div>\r\n");
      out.write("					<div class=\"tiles light\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- partial -->\r\n");
      out.write("			<!-- partial:partials/_navbar.html -->\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"MainPage.do\"><img\r\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<div class=\"nav-profile-text\">MYPAGE</div>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\r\n");
      out.write("								aria-labelledby=\"profileDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\r\n");
      out.write("								</a>\r\n");
      out.write("								\r\n");
      out.write("									<!-- 변경부분 -->\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\r\n");
      out.write("								</a>\r\n");
      out.write("								<!-- 변경부분 -->\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\r\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\r\n");
      out.write("							class=\"nav-link\" href=\"MainPage.do\"> <i\r\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<!-- ** TOP BAR SECTION END ** -->\r\n");
      out.write("			<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<!-- ** Main Area Start ** -->\r\n");
      out.write("\r\n");
      out.write("			<!-- partial -->\r\n");
      out.write("			<div class=\"main-panel\">\r\n");
      out.write("				<div class=\"content-wrapper\">\r\n");
      out.write("					<!--  1행 시작 -->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("							<!--  1행 시작 -->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<!-- 1행 1열 -->\r\n");
      out.write("                  <div class=\"col-lg-8 grid-margin stretch-card\">\r\n");
      out.write("                     <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                           <div class=\"row\">\r\n");
      out.write("                              <!-- 왼쪽에 차트 배치 -->\r\n");
      out.write("                              <div class=\"col-md-7\">\r\n");
      out.write("                                 <h4 class=\"card-title\"><strong class=\"chaname\">표준데이터 비교</strong></h4>\r\n");
      out.write("                                 <canvas id=\"barChart\"></canvas>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- 오른쪽에 표 배치 -->\r\n");
      out.write("                              <div class=\"col-md-4 d-flex flex-column\">\r\n");
      out.write("                                 <table class=\"table\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th scope=\"col\"><strong class=\"chaname\">개인 데이터</strong></th>\r\n");
      out.write("                                          <th scope=\"col\"><strong class=\"chaname\">표준 데이터</strong></th>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <td id=\"mem_height\"></td>\r\n");
      out.write("                                          <td id=\"std_height\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <td id=\"mem_weight\"></td>\r\n");
      out.write("                                          <td id=\"std_weight\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <td id=\"mem_bmi\"></td>\r\n");
      out.write("                                          <td id=\"std_bmi\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <td id=\"mem_muscle\"></td>\r\n");
      out.write("                                          <td id=\"std_muscle\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <td id=\"mem_fat_per\"></td>\r\n");
      out.write("                                          <td id=\"std_fat_per\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                 </table>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("						<!-- 1행 2열 -->\r\n");
      out.write("						<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\"><strong class=\"chaname\">radar 차트로 비교</strong></h4>\r\n");
      out.write("										<canvas id=\"radarChart\">\r\n");
      out.write("									</canvas>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--  1행 끝 -->\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<!-- 사용자 다이어트,뉴스,루틴 추천 -->\r\n");
      out.write("					 <!-- 2행 1열 -->\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("                     <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\" id=\"diet\">\r\n");
      out.write("                           <h2>Diet</h2>\r\n");
      out.write("                           <a href=\"#\" id=\"dietLink\">\r\n");
      out.write("                              <h4 class=\"card-title\" id=\"dietTitle\">Title</h4> \r\n");
      out.write("                              <img src=\"\" alt=\"Diet Image\" id=\"dietImage\" class=\"charimg\"  vertical-align: middle;\r\n");
      out.write("   								height:100%; width: 100%;>\r\n");
      out.write("                           </a>\r\n");
      out.write("                           <canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 2행  2열 -->\r\n");
      out.write("						<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\" id=\"news\">\r\n");
      out.write("									<h2>News</h2>\r\n");
      out.write("									<a href=\"#\" id=\"newsLink\">\r\n");
      out.write("										<h4 class=\"card-title\" id=\"newsTitle\">Title</h4> <img src=\"\"\r\n");
      out.write("										alt=\"News Image\" id=\"newsImage\" vertical-align: middle;\r\n");
      out.write("   								 width: 100%;>\r\n");
      out.write("									</a>\r\n");
      out.write("									<canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 2행 3열 -->\r\n");
      out.write("						<div class=\"col-lg-4 grid-margin stretch-card\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\" id=\"routine\">\r\n");
      out.write("									<h2>Routine</h2>\r\n");
      out.write("									<a href=\"#\" id=\"routineLink\">\r\n");
      out.write("										<h4 class=\"card-title\" id=\"routineTitle\">Title</h4> <img\r\n");
      out.write("										src=\"\" alt=\"Routine Image\" id=\"routineImage\" vertical-align: middle;\r\n");
      out.write("   								 width: 100%;>\r\n");
      out.write("									</a>\r\n");
      out.write("									<canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 사용자 다이어트,뉴스,루틴 추천 끝-->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- ** Main Area END ** -->\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("				<!-- ** Footer Area START ** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- partial:partials/_footer.html -->\r\n");
      out.write("				<footer class=\"footer\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("						<span\r\n");
      out.write("							class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\r\n");
      out.write("							© 2024 <a target=\"_blank\">Fitneeds</a>. All rights reserved.\r\n");
      out.write("						</span> <span\r\n");
      out.write("							class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">\r\n");
      out.write("							Fitneeds team & smhrd <i class=\"mdi mdi-heart text-danger\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</footer>\r\n");
      out.write("				<!-- partial -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- ** Footer Area END ** -->\r\n");
      out.write("				<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- main-panel ends -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- page-body-wrapper ends -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ** All AREA END ** -->\r\n");
      out.write("	<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("	<!-- ** JS AREA START ** -->\r\n");
      out.write("\r\n");
      out.write("	<!-- container-scroller -->\r\n");
      out.write("	<!-- plugins:js -->\r\n");
      out.write("	<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("	<!-- Plugin js for this page -->\r\n");
      out.write("	<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<!-- End plugin js for this page -->\r\n");
      out.write("	<!-- inject:js -->\r\n");
      out.write("	<script src=\"assets/js/off-canvas.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/misc.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/settings.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/todolist.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("	<!-- Custom js for this page -->\r\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/chart.js\"></script>\r\n");
      out.write("	<!-- End custom js for this page -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ** JS AREA START ** -->\r\n");
      out.write("	<!-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("	<!-- flask에서 url받아오기-->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("      // diet 정보 요청\r\n");
      out.write("      fetch('http://127.0.0.1:5000/diet')\r\n");
      out.write("        .then(response => response.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("          console.log(data)\r\n");
      out.write("          document.getElementById('dietLink').href = data.url;\r\n");
      out.write("          document.getElementById('dietImage').src = data.thumb_url;\r\n");
      out.write("          document.getElementById('dietTitle').textContent = data.title;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("      // news 정보 요청\r\n");
      out.write("      fetch('http://127.0.0.1:5000/news')\r\n");
      out.write("        .then(response => response.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("          console.log(data)\r\n");
      out.write("          document.getElementById('newsLink').href = data.url;\r\n");
      out.write("          document.getElementById('newsImage').src = data.thumb_url;\r\n");
      out.write("          document.getElementById('newsTitle').textContent = data.title;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("      // routine 정보 요청\r\n");
      out.write("      fetch('http://127.0.0.1:5000/routine')\r\n");
      out.write("        .then(response => response.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("          console.log(data)\r\n");
      out.write("          document.getElementById('routineLink').href = data.url;\r\n");
      out.write("          document.getElementById('routineImage').src = data.thumb_url;\r\n");
      out.write("          document.getElementById('routineTitle').textContent = data.title;\r\n");
      out.write("        });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
